# Generated by Django 4.2.13 on 2024-06-25 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_handler', '0003_alter_contact_folder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAnalysisParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('TOP', 'Top 10 Most Message'), ('MESSAGES_OVER_TIME', 'Messages over Time'), ('MESSAGES_BY_HOUR', 'Messages Sent by Hour')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactAnalysisParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('MESSAGES_OVER_TIME', 'Messages over Time'), ('WORD_SPECTRUM', 'Word Spectrum')], max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler.contact')),
            ],
        ),
    ]
