# Generated by Django 4.2.13 on 2024-06-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactanalysisparams',
            name='contact',
        ),
        migrations.DeleteModel(
            name='GeneralAnalysisParams',
        ),
        migrations.DeleteModel(
            name='ContactAnalysisParams',
        ),
    ]
