# Generated by Django 4.2.13 on 2024-06-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0002_contact_conversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='folder_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmessage',
            unique_together={('content', 'sender_name', 'timestamp_ms')},
        ),
    ]
